---
#    - name: DOCKER GROUP ADD
#      shell: "sudo groupadd docker"
#      ignore_errors: true

    - name: DOCKER START
      command: service docker start
      ignore_errors: true

    - name: DOCKER USERMOD
      shell: "sudo usermod -aG docker $USER"

    - name: HELLO WORLD
      command: docker run hello-world
      ignore_errors: true