---
- name: SWARM STATUS
  shell: docker node ls
  register: swarm_status
  ignore_errors: true
  tags: swarm

- name: ADD MANAGER
  shell: "docker swarm join --token {{ hostvars['manager']['manager_token']['stdout'] }} {{ hostvars['manager']['ansible_default_ipv4']['address'] }}:2377"
  when: swarm_status.rc != 0
  tags: swarm